version: '3.9'

services:
  # The app service
  app:
    build:
      dockerfile: dev.Dockerfile
      context: .
    networks:
      - serena-network
    ports:
      - "8080:8080" # TODO: make dynamic
    expose:
      - "8080" # TODO: make dynamic
    volumes:
      - .:/app
    env_file:
      - .env

  # The database service
  postgres:
    image: postgres:16
    networks:
      - serena-network
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=testtest
      - POSTGRES_USER=srn_user
      - POSTGRES_DB=serena

networks:
  serena-network:
    driver: bridge

volumes:
    db:
      driver: local
