version: '3.9'

services:
  serena:
    build:
      dockerfile: dev.Dockerfile
      context: .
    networks:
      - serena-network
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - .:/app
    env_file:
      - .env

networks:
  serena-network:
    driver: bridge
