version: '3.9'

services:
  # The app service
  app:
    build:
      dockerfile: dev.Dockerfile
      context: .
    depends_on:
      - postgres
    networks:
      - serena-network
    ports:
      - "${SRN_PORT}:${SRN_PORT}"
    expose:
      - "${SRN_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env

  # The database service
  postgres:
    image: postgres:16
    networks:
      - serena-network
    ports:
      - "${SRN_DB_PORT}:${SRN_DB_PORT}"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${SRN_DB_PASSWORD}
      - POSTGRES_USER=${SRN_DB_USER}
      - POSTGRES_DB=${SRN_DB_NAME}

networks:
  serena-network:
    driver: bridge

volumes:
    db:
      driver: local
