version: '3.9'

services:
  app:
    build:
      dockerfile: dev.Dockerfile
      context: .
    networks:
      - serena-network
    ports:
      - "${SRN_PORT}:${SRN_PORT}"
    expose:
      - "${SRN_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env

networks:
  serena-network:
    driver: bridge
