name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build & Lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest

      - name: Go Vet
        run: go vet ./...

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    container: golang:1.22
    name: Unit & Integration Tests
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: srn_user
          POSTGRES_PASSWORD: testtest
          POSTGRES_DB: serena_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        # Test are run sequentially `-p 1` which is not ideal
        # but necessary for the integration tests to work.
        # We should maybe separate the unit and integration tests.
        run: mkdir build && go test ./... -v -coverprofile=build/coverage.out -p 1
        env:
          SRN_ENV: test
          SRN_PORT: 8080
          SRN_BLOCKCHAIN_WORKER_ENABLED: false
          SRN_BLOCKCHAIN_INTERVAL: 5
          SRN_DB_USER: srn_user
          SRN_DB_PASSWORD: testtest
          SRN_DB_HOST: postgres
          SRN_DB_PORT: 5432
          SRN_DB_NAME: serena_test

      - name: Check coverage
        run: ./.github/coverage
        env:
          SRN_MIN_COVERAGE: 80