name: CI workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
#      - edited
#      - unlocked

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest

      - name: Build
        run: go build -v ./...

      # TODO: we may need container-job with a PostgreSQL service here
      - name: Test
        run: go test -v -cover ./...
        env:
          SRN_ENV: test
