name: CI workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
#      - edited
#      - unlocked

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    container: golang:1.22
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: srn_user
          POSTGRES_PASSWORD: testtest
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test
        run: go test -v -cover ./...
        env:
          SRN_ENV: test
          SRN_PORT: 8080
          SRN_BLOCKCHAIN_WORKER_ENABLED: false
          SRN_BLOCKCHAIN_INTERVAL: 5
          SRN_DB_USER: srn_user
          SRN_DB_PASSWORD: testtest
          SRN_DB_HOST: postgres
          SRN_DB_PORT: 5432
          SRN_DB_NAME: postgres
